// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package myMsg

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MyMsg struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyMsg) Reset()         { *m = MyMsg{} }
func (m *MyMsg) String() string { return proto.CompactTextString(m) }
func (*MyMsg) ProtoMessage()    {}
func (*MyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *MyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyMsg.Unmarshal(m, b)
}
func (m *MyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyMsg.Marshal(b, m, deterministic)
}
func (m *MyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyMsg.Merge(m, src)
}
func (m *MyMsg) XXX_Size() int {
	return xxx_messageInfo_MyMsg.Size(m)
}
func (m *MyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_MyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_MyMsg proto.InternalMessageInfo

func (m *MyMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MyMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MyMsg) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MyMsg)(nil), "myMsg.MyMsg")
	proto.RegisterType((*Error)(nil), "myMsg.Error")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x46, 0x69, 0x35, 0x4a, 0x0f, 0xed, 0x70, 0x38, 0x04, 0x27, 0xed, 0xe4, 0x20, 0x1d, 0x74,
	0x76, 0x70, 0x70, 0xec, 0x52, 0xf0, 0x07, 0x54, 0x7b, 0x84, 0x80, 0x31, 0x72, 0x17, 0x07, 0xff,
	0xbd, 0x78, 0xb5, 0xdb, 0xf7, 0xde, 0xf0, 0xf1, 0xa0, 0x08, 0xe2, 0xea, 0x17, 0xc7, 0x14, 0xd1,
	0x84, 0x4f, 0x23, 0xae, 0x3a, 0x83, 0x69, 0x7e, 0x03, 0x4b, 0xc8, 0x7d, 0x6f, 0xb3, 0x4d, 0xb6,
	0x2b, 0xda, 0xdc, 0xf7, 0x88, 0x30, 0x7d, 0x76, 0x81, 0x6c, 0xae, 0x46, 0x37, 0xae, 0xc0, 0x50,
	0xe8, 0xfc, 0xc3, 0x4e, 0x54, 0x0e, 0x50, 0x6d, 0xc1, 0x5c, 0x98, 0x23, 0xa3, 0x85, 0x79, 0x20,
	0x91, 0xce, 0xd1, 0xff, 0x67, 0xc4, 0xc3, 0x09, 0x96, 0xf7, 0xb7, 0xa4, 0x18, 0x9a, 0x41, 0xe0,
	0x1e, 0xca, 0xab, 0x10, 0xb7, 0xe4, 0xbc, 0x24, 0x62, 0xea, 0x71, 0x51, 0x6b, 0x50, 0xad, 0x35,
	0xeb, 0x91, 0xf4, 0xf8, 0x36, 0xd3, 0xe4, 0xe3, 0x37, 0x00, 0x00, 0xff, 0xff, 0x40, 0x62, 0x4d,
	0x06, 0xbf, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomMessageClient is the client API for CustomMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomMessageClient interface {
	UserRegistered(ctx context.Context, in *MyMsg, opts ...grpc.CallOption) (*Error, error)
}

type customMessageClient struct {
	cc *grpc.ClientConn
}

func NewCustomMessageClient(cc *grpc.ClientConn) CustomMessageClient {
	return &customMessageClient{cc}
}

func (c *customMessageClient) UserRegistered(ctx context.Context, in *MyMsg, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/myMsg.customMessage/UserRegistered", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomMessageServer is the server API for CustomMessage service.
type CustomMessageServer interface {
	UserRegistered(context.Context, *MyMsg) (*Error, error)
}

// UnimplementedCustomMessageServer can be embedded to have forward compatible implementations.
type UnimplementedCustomMessageServer struct {
}

func (*UnimplementedCustomMessageServer) UserRegistered(ctx context.Context, req *MyMsg) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRegistered not implemented")
}

func RegisterCustomMessageServer(s *grpc.Server, srv CustomMessageServer) {
	s.RegisterService(&_CustomMessage_serviceDesc, srv)
}

func _CustomMessage_UserRegistered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomMessageServer).UserRegistered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myMsg.customMessage/UserRegistered",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomMessageServer).UserRegistered(ctx, req.(*MyMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomMessage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myMsg.customMessage",
	HandlerType: (*CustomMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserRegistered",
			Handler:    _CustomMessage_UserRegistered_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}
